name: CI

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and publish gem
      uses: jstastny/publish-gem-to-github@v1.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: rangeroob